#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum BodyKind {
    Star,
    Planet,
    DwarfPlanet,
    Moon,
    Exoplanet,
}

impl BodyKind {
    pub fn label(self) -> &'static str {
        match self {
            BodyKind::Star => "Star",
            BodyKind::Planet => "Planet",
            BodyKind::DwarfPlanet => "Dwarf Planet",
            BodyKind::Moon => "Moon",
            BodyKind::Exoplanet => "Exoplanet",
        }
    }
}

#[derive(PartialEq)]
pub struct CelestialBody {
    pub name: &'static str,
    pub kind: BodyKind,
    pub tagline: &'static str,
    pub distance: &'static str,
    pub diameter: &'static str,
    pub day_length: &'static str,
    pub year_length: &'static str,
    pub moons: &'static str,
    pub gravity_label: &'static str,
    pub gravity_g: f32,
    pub description: &'static str,
    pub top_color: (u8, u8, u8),
    pub bottom_color: (u8, u8, u8),
    pub glow_color: (u8, u8, u8),
    pub has_ring: bool,
    pub related: &'static [usize],
}

pub const SUN: usize = 0;
pub const MERCURY: usize = 1;
pub const VENUS: usize = 2;
pub const EARTH: usize = 3;
pub const MOON: usize = 4;
pub const MARS: usize = 5;
pub const JUPITER: usize = 6;
pub const EUROPA: usize = 7;
pub const SATURN: usize = 8;
pub const TITAN: usize = 9;
pub const URANUS: usize = 10;
pub const NEPTUNE: usize = 11;
pub const PLUTO: usize = 12;
pub const PROXIMA_B: usize = 13;

pub static BODIES: &[CelestialBody] = &[
    CelestialBody {
        name: "Sun",
        kind: BodyKind::Star,
        tagline: "The star that lights the solar system",
        distance: "Center of the solar system",
        diameter: "1,391,000 km",
        day_length: "~27 days (equator)",
        year_length: "—",
        moons: "0",
        gravity_label: "27.9 g",
        gravity_g: 27.9,
        description: "A G-type main-sequence star that fuses hydrogen into helium in its core, radiating the light and heat that make every other body on this list visible. It holds more than 99.8% of the solar system's mass and its gravity is what everything else orbits.",
        top_color: (255, 232, 168),
        bottom_color: (255, 122, 0),
        glow_color: (255, 176, 64),
        has_ring: false,
        related: &[MERCURY, EARTH, JUPITER],
    },
    CelestialBody {
        name: "Mercury",
        kind: BodyKind::Planet,
        tagline: "Closest to the Sun, scorched and cratered",
        distance: "57.9 million km from the Sun",
        diameter: "4,879 km",
        day_length: "176 Earth days",
        year_length: "88 Earth days",
        moons: "0",
        gravity_label: "0.38 g",
        gravity_g: 0.38,
        description: "The smallest and innermost planet, with almost no atmosphere to hold heat: daytime temperatures pass 400°C while nights fall below -180°C. Its heavily cratered surface has barely changed in billions of years.",
        top_color: (196, 190, 180),
        bottom_color: (74, 68, 60),
        glow_color: (168, 158, 142),
        has_ring: false,
        related: &[SUN, VENUS],
    },
    CelestialBody {
        name: "Venus",
        kind: BodyKind::Planet,
        tagline: "The hottest planet, wrapped in acid clouds",
        distance: "108.2 million km from the Sun",
        diameter: "12,104 km",
        day_length: "243 Earth days (retrograde)",
        year_length: "225 Earth days",
        moons: "0",
        gravity_label: "0.90 g",
        gravity_g: 0.90,
        description: "A runaway greenhouse effect traps heat under a thick carbon-dioxide atmosphere, making Venus the hottest planet even though Mercury sits closer to the Sun. It spins backward compared to most planets, so slowly that its day is longer than its year.",
        top_color: (238, 214, 165),
        bottom_color: (122, 84, 40),
        glow_color: (232, 196, 140),
        has_ring: false,
        related: &[MERCURY, EARTH],
    },
    CelestialBody {
        name: "Earth",
        kind: BodyKind::Planet,
        tagline: "The only known world with life",
        distance: "149.6 million km from the Sun",
        diameter: "12,742 km",
        day_length: "24 hours",
        year_length: "365.25 days",
        moons: "1",
        gravity_label: "1.00 g",
        gravity_g: 1.0,
        description: "Liquid water oceans, a breathable atmosphere, and a protective magnetic field make Earth the only place known to host life. Its single large Moon stabilizes its axial tilt and drives the ocean tides.",
        top_color: (110, 168, 224),
        bottom_color: (24, 48, 84),
        glow_color: (96, 168, 232),
        has_ring: false,
        related: &[MOON, MARS, PROXIMA_B],
    },
    CelestialBody {
        name: "Moon",
        kind: BodyKind::Moon,
        tagline: "Earth's only natural satellite",
        distance: "384,400 km from Earth",
        diameter: "3,474 km",
        day_length: "27.3 days (tidally locked)",
        year_length: "27.3 days around Earth",
        moons: "—",
        gravity_label: "0.17 g",
        gravity_g: 0.165,
        description: "Tidally locked so the same face always points at Earth, the Moon likely formed from debris after a Mars-sized body struck the young Earth. Its pull raises the ocean tides and has slowly stretched Earth's day longer over billions of years.",
        top_color: (214, 212, 208),
        bottom_color: (70, 70, 72),
        glow_color: (190, 190, 194),
        has_ring: false,
        related: &[EARTH],
    },
    CelestialBody {
        name: "Mars",
        kind: BodyKind::Planet,
        tagline: "The red planet, home to the tallest volcano",
        distance: "227.9 million km from the Sun",
        diameter: "6,779 km",
        day_length: "24h 37m",
        year_length: "687 Earth days",
        moons: "2",
        gravity_label: "0.38 g",
        gravity_g: 0.38,
        description: "Iron oxide dust gives Mars its rust-red color. It hosts Olympus Mons, the tallest volcano in the solar system, and Valles Marineris, a canyon system long enough to stretch across the continental United States. Two small, irregular moons, Phobos and Deimos, orbit close overhead.",
        top_color: (224, 132, 96),
        bottom_color: (92, 42, 26),
        glow_color: (214, 110, 78),
        has_ring: false,
        related: &[EARTH, JUPITER],
    },
    CelestialBody {
        name: "Jupiter",
        kind: BodyKind::Planet,
        tagline: "The largest planet, wrapped in storms",
        distance: "778.5 million km from the Sun",
        diameter: "139,820 km",
        day_length: "9h 56m",
        year_length: "11.9 Earth years",
        moons: "95",
        gravity_label: "2.53 g",
        gravity_g: 2.53,
        description: "A gas giant more massive than every other planet combined, banded by fast-moving cloud belts. The Great Red Spot is a storm wider than Earth that has raged for centuries. Its moon Europa is one of the most promising places to search for life beyond Earth.",
        top_color: (232, 202, 164),
        bottom_color: (120, 78, 40),
        glow_color: (224, 176, 120),
        has_ring: false,
        related: &[EUROPA, SATURN, MARS],
    },
    CelestialBody {
        name: "Europa",
        kind: BodyKind::Moon,
        tagline: "An icy moon hiding an ocean",
        distance: "671,000 km from Jupiter",
        diameter: "3,122 km",
        day_length: "3.5 days (tidally locked)",
        year_length: "3.5 days around Jupiter",
        moons: "—",
        gravity_label: "0.13 g",
        gravity_g: 0.134,
        description: "Beneath a smooth, cracked shell of ice, Europa is thought to hide a liquid-water ocean warmed by Jupiter's tidal flexing. That combination of water, warmth and chemistry makes it one of the solar system's best candidates for finding life.",
        top_color: (232, 220, 196),
        bottom_color: (128, 110, 84),
        glow_color: (222, 206, 176),
        has_ring: false,
        related: &[JUPITER],
    },
    CelestialBody {
        name: "Saturn",
        kind: BodyKind::Planet,
        tagline: "Famous for its dazzling ring system",
        distance: "1.43 billion km from the Sun",
        diameter: "116,460 km",
        day_length: "10h 33m",
        year_length: "29.4 Earth years",
        moons: "146+",
        gravity_label: "1.06 g",
        gravity_g: 1.06,
        description: "Saturn is a gas giant so light for its size that it would float in water. Its rings are made of countless chunks of ice and rock, some as small as dust and others as large as houses, spread across a system wider than the distance from Earth to the Moon.",
        top_color: (238, 220, 168),
        bottom_color: (140, 112, 58),
        glow_color: (230, 208, 150),
        has_ring: true,
        related: &[TITAN, JUPITER, URANUS],
    },
    CelestialBody {
        name: "Titan",
        kind: BodyKind::Moon,
        tagline: "A hazy moon with methane lakes",
        distance: "1.2 million km from Saturn",
        diameter: "5,150 km",
        day_length: "16 days (tidally locked)",
        year_length: "16 days around Saturn",
        moons: "—",
        gravity_label: "0.14 g",
        gravity_g: 0.14,
        description: "The only moon in the solar system with a thick atmosphere, Titan has weather, rivers, and lakes — but made of liquid methane and ethane instead of water, under skies far too cold for it to freeze or boil away.",
        top_color: (232, 176, 108),
        bottom_color: (122, 76, 32),
        glow_color: (224, 160, 92),
        has_ring: false,
        related: &[SATURN],
    },
    CelestialBody {
        name: "Uranus",
        kind: BodyKind::Planet,
        tagline: "An ice giant tipped on its side",
        distance: "2.87 billion km from the Sun",
        diameter: "50,724 km",
        day_length: "17h 14m (retrograde)",
        year_length: "84 Earth years",
        moons: "27",
        gravity_label: "0.89 g",
        gravity_g: 0.89,
        description: "A collision long ago is thought to have knocked Uranus onto its side, so it rolls around the Sun almost like a ball rather than spinning upright. Methane in its atmosphere absorbs red light, giving it a pale blue-green color.",
        top_color: (188, 224, 224),
        bottom_color: (74, 128, 130),
        glow_color: (176, 220, 220),
        has_ring: true,
        related: &[NEPTUNE, SATURN],
    },
    CelestialBody {
        name: "Neptune",
        kind: BodyKind::Planet,
        tagline: "The windiest world in the solar system",
        distance: "4.5 billion km from the Sun",
        diameter: "49,244 km",
        day_length: "16h 6m",
        year_length: "165 Earth years",
        moons: "14",
        gravity_label: "1.14 g",
        gravity_g: 1.14,
        description: "Deep blue and the most distant known planet, Neptune has the fastest winds ever recorded on a planet, gusting past 2,000 km/h. It was found by mathematics before anyone saw it: astronomers predicted its position from wobbles in Uranus's orbit.",
        top_color: (100, 132, 224),
        bottom_color: (28, 42, 108),
        glow_color: (96, 128, 224),
        has_ring: false,
        related: &[URANUS, PLUTO],
    },
    CelestialBody {
        name: "Pluto",
        kind: BodyKind::DwarfPlanet,
        tagline: "A distant dwarf planet with a heart",
        distance: "5.9 billion km from the Sun",
        diameter: "2,377 km",
        day_length: "6.4 Earth days",
        year_length: "248 Earth years",
        moons: "5",
        gravity_label: "0.06 g",
        gravity_g: 0.063,
        description: "Reclassified as a dwarf planet in 2006, Pluto orbits in the icy Kuiper Belt beyond Neptune. Its largest moon, Charon, is so massive by comparison that the two orbit a point in open space between them. A vast, heart-shaped plain of nitrogen ice, Tombaugh Regio, spans much of one hemisphere.",
        top_color: (224, 206, 186),
        bottom_color: (98, 82, 68),
        glow_color: (214, 196, 176),
        has_ring: false,
        related: &[NEPTUNE, MOON],
    },
    CelestialBody {
        name: "Proxima Centauri b",
        kind: BodyKind::Exoplanet,
        tagline: "The nearest known world beyond our own",
        distance: "4.24 light-years from Earth",
        diameter: "Roughly Earth-sized (unconfirmed)",
        day_length: "Likely tidally locked",
        year_length: "11.2 days",
        moons: "Unknown",
        gravity_label: "~1.1 g (estimated)",
        gravity_g: 1.1,
        description: "Orbiting the red dwarf Proxima Centauri, the closest star to the Sun, this is the nearest known exoplanet to Earth. It sits in its star's habitable zone, where liquid water could exist, but its exact size, atmosphere, and habitability are still unconfirmed.",
        top_color: (214, 138, 108),
        bottom_color: (64, 26, 20),
        glow_color: (200, 90, 64),
        has_ring: false,
        related: &[SUN],
    },
];
